### ISSUE TITLE
The "path" argument must be of type string. Received function chunkFilename

### ISSUE THREAD

**Issue by BooStudio** [ctf0/laravel-mix-versionhash#45]
I have been using this plugin for some time now but it doesn't seem to work with the latest mix version I recon,

it gives error -
```js
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received function chunkFilename
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.dirname (node:path:1172:5)
    at VersionHash.webpackConfig (/Users/files/node_modules/laravel-mix-versionhash/src/index.js:78:34)
    at /Users/files/node_modules/laravel-mix/src/components/ComponentRegistrar.js:106:54
    at /Users/files/node_modules/laravel-mix/src/Dispatcher.js:37:62
    at Array.map (<anonymous>)
    at Dispatcher.fire (/Users/filesnode_modules/laravel-mix/src/Dispatcher.js:37:47)
    at Mix.dispatch (/Users/filees/node_modules/laravel-mix/src/Mix.js:224:32)
    at WebpackConfig.build (/Users/files/node_modules/laravel-mix/src/builder/WebpackConfig.js:36:19)
    at async /Users/files/node_modules/webpack-cli/lib/webpack-cli.js:1222:37
    at async Promise.all (index 0)
    at async evaluateConfig (/Users/files/node_modules/webpack-cli/lib/webpack-cli.js:1213:35)
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig (/Users/files/node_modules/webpack-cli/lib/webpack-cli.js:1244:38)
    at async WebpackCLI.createCompiler (/Users/files/node_modules/webpack-cli/lib/webpack-cli.js:1670:22) {
  code: 'ERR_INVALID_ARG_TYPE'
```
I tried some edits to the plugin, which makes it work it's dirty but it's working for now,

Edit in index.js

![Screen Shot 2021-02-16 at 4 35 04 pm](https://user-images.githubusercontent.com/54012426/108022579-ed055900-7074-11eb-8cfa-4584fa799faf.png)

changed this line 'webpackConfig.output.chunkFilename' to 'typeof webpackConfig.output.chunkFilename != "function" '

**Comment by ctf0** [comment]
can u make a pr with the changes ?

**Comment by BooStudio** [comment]
Donski mate!

**Comment by BooStudio** [comment]
#47

**Comment by mareshyn** [comment]
Sweet! Could you release this fix, please? 🙏🏾

**Comment by ctf0** [comment]
done
